apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-ms
  namespace: banking
  labels:
    app: accounts-ms
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-ms
  template:
    metadata:
      labels:
        app: accounts-ms
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port:   "8081"
        prometheus.io/path:   "/actuator/prometheus"
    spec:
      serviceAccountName: accounts-ms-sa
      containers:
        - name: accounts-ms
          image: YOUR_DOCKERHUB/rewabank-accounts-ms:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: accounts-ms-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: accounts-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accounts-db-secret
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu:    "250m"
            limits:
              memory: "512Mi"
              cpu:    "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10