server:
  port: 8114
spring:
  application:
    name: "customers"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5432/customersdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 7250
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8000/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      rabbitmq:
        binder:
          host: "localhost"
          port: 5672
          username: "guest"
          password: "guest"
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

endpoints:
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true

info:
  app:
    name: "customer"
    description: "Eazy Bank Customer Application"
    version: "1.0.0"

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_ID},%X{span_id}]"
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    com:
      RewaBank:
        cards: DEBUG

resilience4j.circuitBreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1
axon:
  eventhandling:
    processors:
      customer-group:
        mode: subscribing
  axonserver:
    servers: localhost:8124
    enabled: false
    context: default