apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-ms-config
  namespace: banking
data:
  KEYCLOAK_URL:    "http://keycloak.keycloak.svc.cluster.local:8080"
  KEYCLOAK_REALM:  "rewabank"
  KAFKA_BOOTSTRAP: "kafka-service.banking.svc.cluster.local:9092"
  REDIS_HOST:      "redis-service.banking.svc.cluster.local"
  DB_URL:          "jdbc:postgresql://auth-db.banking.svc.cluster.local:5432/auth_db"