spring:
  application:
      name: "discoveryserver"
  config:
    import: "optional:configserver:http://localhost:8000/"
management:
  endpoints:
     web:
       exposure:
            include: "*"
  health:
     readiness-state:
        enabled: true
     liveness-state:
        enabled: true
  endpoint:
     health:
       probes:
          enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      RewaBank:
        loans: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_ID},%X{span_id}]"