server:
  port: 3333
spring:
  application:
    name: "Transaction-Service"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5432/rewabankdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 7250
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        transaction-events-out-0:
          destination: transaction-events

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7070/realms/banking

keycloak:
  realm: banking
  auth-server-url: http://localhost:8080/auth
  resource: transaction-service
  credentials:
    secret: your-client-secret

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 10
