server:
  port: 8112
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5432/loansdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 7250  # Change this in production!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use "validate" in production
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8000/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      rabbitmq:
        binder:
          host: "localhost"
          port: 5672
          username: "guest"
          password: "guest"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

endpoints:
  shutdown:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true

info:
  app:
    name:
      description: "RewaBank loans Application"
      version: "1.0.0"

logging:
  level:
    com:
      RewaBank:
        loans: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_ID},%X{span_id}]"

axon:
  eventhandling:
    processors:
      loan-group:
        mode: subscribing
  axonserver:
    servers: localhost:8124
    enabled: false
    context: default

