server:
  port: 2222

spring:
  application:
    name: "Notification-Service"

  mail:
    host: smtp.yourmailprovider.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092

  twilio:
    account-sid: YOUR_TWILIO_ACCOUNT_SID
    auth-token: YOUR_TWILIO_AUTH_TOKEN
    from-number: YOUR_TWILIO_PHONE_NUMBER
