apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: cards-ms-policy
  namespace: banking
spec:
  selector:
    matchLabels:
      app: cards-ms
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/banking/sa/api-gateway-sa
      to:
        - operation:
            methods: ["GET","POST","PATCH"]
            paths:
              - /api/v1/cards
              - /api/v1/cards/*
    - from:
        - source:
            namespaces:
              - monitoring
              - istio-system
      to:
        - operation:
            paths:
              - /actuator/health
              - /actuator/prometheus