apiVersion: v1
kind: ConfigMap
metadata:
  name: cards-ms-config
  namespace: banking
data:
  KEYCLOAK_JWKS_URI:    "http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/rewabank/protocol/openid-connect/certs"
  # ADDED: issuer must match JWT iss claim — uses localhost (frontendUrl)
  KEYCLOAK_ISSUER_URI:  "http://localhost/auth/realms/rewabank"
  KAFKA_BOOTSTRAP:      "kafka-kafka-bootstrap.banking.svc.cluster.local:9092"
  DB_URL:               "jdbc:postgresql://postgresql-rw.banking.svc.cluster.local:5432/cards_db"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4318/v1/traces"