spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8000/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#config for gateway response timeout also known as global response timeout.
      httpclient:
        connect-timeout: 1000
        response-timeout: 15s
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7070/realms/rewabank-realm/protocol/openid-connect/certs"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name:
      description: "RewaBank Gateway Server Application"
      version: "1.0.0"

logging:
  level:
    com:
      rewabank:
        gatewayserver: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_ID},%X{span_id}]"

resilience4j.circuitBreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

