#This is a yaml formatted file
#declared variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: usnamemonu/loans
  tag: v1
  
containerPort: 8111

service:
  type: ClusterIP
  port: 8111
  targetPort: 8111
  
appname_enabled: true
profile-enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false
