build:
  version: "3.0"

cards:
  message: "Welcome to rewabank accounts related local APIs "
  contactDetails:
    name: "mukesh kushwaha - Developer"
    email: "mukesh@rewabank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
