apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: banking
data:
  CORS_ORIGIN_MOBILE: http://localhost:3000
  CORS_ORIGIN_WEB: http://localhost:4200
  KEYCLOAK_ISSUER_URI: http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth/realms/rewabank
  KEYCLOAK_JWKS_URI: http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth/realms/rewabank/protocol/openid-connect/certs
  REDIS_HOST: valkey.banking.svc.cluster.local
  REDIS_PORT: "6379"
  SPRING_CLOUD_CONSUL_CONFIG_ENABLED: "false"
  SPRING_CLOUD_CONSUL_CONFIG_IMPORT_CHECK_ENABLED: "false"
