apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: banking
data:
  application.yml: |
    cors:
      allowed-origins:
        - http://localhost:4200
    logging:
      level:
        com.rewabank: INFO