apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: customers-ms-mtls
  namespace: banking
spec:
  selector:
    matchLabels:
      app: customers-ms
  mtls:
    mode: STRICT