apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: banking
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8072
      targetPort: 8072
      protocol: TCP
  type: ClusterIP