#This is a yaml formatted file
#declared variables to be passed into your templates.

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: usnamemonu/cards
  tag: v1
  
containerPort: 8112

service:
  type: ClusterIP
  port: 8112
  targetPort: 8112
  
appname_enabled: true
profile-enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false
