server:
  port: 8092
  error:
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: cards-ms

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgresql-rw.banking.svc.cluster.local:5432/cards_db}
    username: ${DB_USERNAME:cards_user}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka-kafka-bootstrap.banking.svc.cluster.local:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: cards-ms
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.rewabank,java.util,java.time,java.math"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

feign:
  customers-ms:
    url: ${CUSTOMERS_SERVICE_URL:http://customers-service.banking.svc.cluster.local:8080}
  accounts-ms:
    url: ${ACCOUNTS_SERVICE_URL:http://accounts-service.banking.svc.cluster.local:8081}
  fraud-ms:
    url: ${FRAUD_SERVICE_URL:http://fraud-service.banking.svc.cluster.local:8094}
  notification-ms:
    url: ${NOTIFICATIONS_SERVICE_URL:http://notifications-service.banking.svc.cluster.local:9010}

encryption:
  aes-key: ${AES_ENCRYPTION_KEY}

kafka:
  topics:
    card-issued:  bank.card.issued
    card-blocked: bank.card.blocked

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector.monitoring.svc.cluster.local:4318/v1/traces}

card:
  cvv:
    bcrypt-strength: 5   # 2^5=32 iterations — fast for CVV verification on every transaction

logging:
  level:
    com.rewabank: INFO
  pattern:
    level: "%5p[${spring.application.name},%X{traceId},%X{spanId}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"