apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-ms-config
  namespace: banking
data:
  DB_URL:                "jdbc:postgresql://postgresql-rw.banking.svc.cluster.local:5432/accounts_db"
  REDIS_HOST:            "valkey.banking.svc.cluster.local"
  KAFKA_BOOTSTRAP:       "kafka-kafka-bootstrap.banking.svc.cluster.local:9092"
  KEYCLOAK_JWKS_URI:     "http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth/realms/rewabank/protocol/openid-connect/certs"
  CUSTOMERS_SERVICE_URL: "http://customers-service.banking.svc.cluster.local:8080"
