apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: banking
  labels:
    app: auth-ms
spec:
  selector:
    app: auth-ms
  ports:
    - name: http
      port: 8073
      targetPort: 8073
  type: ClusterIP