apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
        - name: cards
          image: usnamemonu/cards:v1
          ports:
            - containerPort: 8111
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: rewabank-configmap
                  key: CARDS_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: rewabank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: rewabank-configmap
                  key: SPRING_CONFIG_IMPORT
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:
                valueFrom:
                  configMapKeyRef:
                    name: rewabank-configmap
                    key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE


---
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8111


