CREATE TABLE transactions (
    id                          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    idempotency_key             VARCHAR(100)  NOT NULL UNIQUE,
    keycloak_user_id            VARCHAR(255)  NOT NULL,
    source_account_id           UUID          NOT NULL,
    destination_account_id      UUID          NOT NULL,
    source_account_number       VARCHAR(12)   NOT NULL,
    destination_account_number  VARCHAR(12)   NOT NULL,
    amount                      NUMERIC(19,4) NOT NULL,
    currency                    VARCHAR(3)    NOT NULL DEFAULT 'INR',
    transaction_type            VARCHAR(20)   NOT NULL,
    status                      VARCHAR(15)   NOT NULL DEFAULT 'INITIATED',
    remarks                     VARCHAR(500),
    reference_number            VARCHAR(30)   UNIQUE,
    fraud_score                 INTEGER,
    fraud_action                VARCHAR(10),
    debit_completed             BOOLEAN       NOT NULL DEFAULT FALSE,
    credit_completed            BOOLEAN       NOT NULL DEFAULT FALSE,
    reversal_reason             TEXT,
    reversed_at                 TIMESTAMP,
    completed_at                TIMESTAMP,
    failure_reason              TEXT,
    ip_address                  VARCHAR(45),
    device_id                   VARCHAR(255),
    created_at                  TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP     NOT NULL DEFAULT NOW()
);