server:
  port: 5555  # Port on which the Verification-Service will run

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rewabankdb
    username: root
    password: 7250
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    stream:
      bindings:
        verification-in-0:
          destination: verification-requests
          group: ${spring.application.name}
        verification-out-0:
          destination: verification-responses
      kafka:
        binder:
          brokers:
            - localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/rewabank-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/rewabank-realm
        registration:
          keycloak:
            client-id: your-client-id
            client-secret: your-client-secret
            authorization-grant-type: client_credentials
            scope: openid

  mail:
    host: smtp.yourmailprovider.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account-sid: your-twilio-account-sid
  auth-token: your-twilio-auth-token
  from-number: your-twilio-phone-number

logging:
  level:
    com.verification: DEBUG

