apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: banking
  labels:
    app: accounts-ms
spec:
  selector:
    app: accounts-ms
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP