apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-ms
  namespace: banking
  labels:
    app: notifications-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-ms
  template:
    metadata:
      labels:
        app: notifications-ms
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port:   "9010"
        prometheus.io/path:   "/actuator/prometheus"
    spec:
      serviceAccountName: notifications-ms-sa
      containers:
        - name: notifications-ms
          image: rewabank/rewabank-notifications-ms:latest
          ports:
            - containerPort: 9010
          envFrom:
            - configMapRef:
                name: notifications-ms-config
          resources:
            requests:
              memory: "256Mi"
              cpu:    "250m"
            limits:
              memory: "512Mi"
              cpu:    "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9010
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9010
            initialDelaySeconds: 30
            periodSeconds: 10
