apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-ms-config
  namespace: banking
data:
  KAFKA_BOOTSTRAP:   "kafka-kafka-bootstrap.banking.svc.cluster.local:9092"
  KEYCLOAK_JWKS_URI: "http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/rewabank/protocol/openid-connect/certs"
  KEYCLOAK_ISSUER_URI: "http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/rewabank"
  MONGODB_URI:       "mongodb://root:mongodb@2024@mongodb-svc.banking.svc.cluster.local:27017/notifications_db?authSource=admin"
