apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-ms-config
  namespace: banking
data:
  KEYCLOAK_JWKS_URI:    "http://keycloak.keycloak.svc.cluster.local:8080/realms/rewabank/protocol/openid-connect/certs"
  KAFKA_BOOTSTRAP:      "kafka-service.banking.svc.cluster.local:9092"
  REDIS_HOST:           "redis-service.banking.svc.cluster.local"
  DB_URL:               "jdbc:postgresql://accounts-db.banking.svc.cluster.local:5432/accounts_db"
  CUSTOMERS_SERVICE_URL: "http://customers-service.banking.svc.cluster.local:8080"